#!/bin/bash

# ### TODO args
# ##INP=$1
#INP="-Is /bin/bash"

PROJECT="$1"
MINUTES="$2"
NNODES="$3"
INP="$4"
#EXTRAS="-alloc_flags \"gpumps smt4\""
EXTRAS="${@:5}"

JOBSCRIPT="jobscript.lsf"


bsub "$EXTRAS" -P "$PROJECT" -W "0:$MINUTES" -nnodes "$NNODES" "$INP" "$JOBSCRIPT"
